<?php

  /**
   * Implements hook_entity_insert().
   */
  function static_custom_api_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {
      \Drupal::service("static_custom_api.files_cache")->saveEntity($entity);
      \Drupal::service("static_custom_api.alias_cache")->saveAliasByEntity($entity);

  }
  
  /**
   * Implements hook_entity_update().
   */
  function static_custom_api_entity_update(\Drupal\Core\Entity\EntityInterface $entity) {
    \Drupal::service("static_custom_api.files_cache")->saveEntity($entity);
    \Drupal::service("static_custom_api.alias_cache")->saveAliasByEntity($entity);


  }
  
  /**
   * Implements hook_entity_delete().
   */
  function static_custom_api_entity_delete(\Drupal\Core\Entity\EntityInterface $entity) {
      \Drupal::service("static_custom_api.files_cache")->removeEntity($entity);
  }

  /**
   * Implements hook_entity_predelete().
   */
  function static_custom_api_entity_predelete(\Drupal\Core\Entity\EntityInterface $entity) {
    \Drupal::service("static_custom_api.alias_cache")->removeAlias($entity);

  }
